name: CI - Test app with Docker

on:
  push:
  pull_request:

jobs:
  swapi-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login to Docker Hub 
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build and start all services
      - name: Start application with docker-compose
        working-directory: swapi_webapp/
        run: |
          docker compose down -v
          docker compose up -d --build

      # # 4. Wait for services (optional but recommended)
      # - name: Wait for services to be ready
      #   run: |
      #     echo "Waiting for services..."
      #     for i in {1..2}; do
      #       if docker ps | grep "healthy" >/dev/null; then
      #         echo "Containers are healthy!"
      #         break
      #       fi
      #       echo "Waiting..."
      #       sleep 5
      #     done

      # # 5. Install testing dependencies
      # - name: Install testing dependencies
      #   working-directory: tests/
      #   run: |
      #     pip install -r requirements-dev.txt


      # 6. Run tests inside the webapp container
      - name: Run tests
        working-directory: swapi_webapp/
        run: |
          docker compose exec -T webapp pytest -q tests/

      # 7. Shut down docker-compose **always**
      - name: Shut down docker-compose
        working-directory: swapi_webapp/
        if: always()
        run: docker compose down -v

      # Push the Image to Docker Hub (Continuous Delivery)
      - name: Push Image to Docker Hub 
        run: |
          docker tag swapi_webapp:mysql ${{ secrets.DOCKERHUB_USERNAME }}/swapi_webapp:mysql
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/swapi_webapp-webapp:mysql
